server.port=8080

db.url=jdbc:postgresql://localhost:5432/bonus_server
db.username=username
db.password=password

hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
hibernate.hbm2ddl.auto=none
hibernate.generate_ddl=false
hibernate.show_sql=true

liquibase.changelog=classpath:migrations/db.changelog-master.xml
liquibase.enabled=true