--liquibase formatted sql

--changeset e_pozdnyakova:01.000.00-create-user
CREATE TABLE users
(
    id       BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    login    VARCHAR(32) NOT NULL UNIQUE,
    password VARCHAR(60) NOT NULL,
    role     VARCHAR(32) NOT NULL
);