--liquibase formatted sql

--changeset e_pozdnyakova:01.000.00-create-bonus-operation
CREATE TABLE bonus_operation
(
    id                     BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    account_id             BIGINT         NOT NULL,
    type_operation         VARCHAR(32)    NOT NULL,
    cancelled_operation_id BIGINT,
    amount_bonus           NUMERIC(19, 2) NOT NULL,
    status                 VARCHAR(32)    NOT NULL,
    creation_at            TIMESTAMP      NOT NULL,
    version                BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT fk_bonus_operation_account
        FOREIGN KEY (account_id) REFERENCES bonus_account (id),
    CONSTRAINT fk_bonus_operation_cancelled
        FOREIGN KEY (cancelled_operation_id) REFERENCES bonus_operation (id)
);