--liquibase formatted sql

--changeset e_pozdnyakova:01.000.00-create-bonus-account
CREATE TABLE bonus_account
(
    id          BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
    card_number VARCHAR(16)    NOT NULL UNIQUE,
    balance     NUMERIC(19, 2) NOT NULL,
    version     BIGINT         NOT NULL DEFAULT 0,
    CONSTRAINT chk_bonus_account_card_number_format CHECK (card_number ~ '^\d{16}$')
);
